apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name}}
    tag: {{ .Values.tag}}
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Values.name}}
    tag: {{ .Values.tag}}
  type: {{ .Values.service.type}}