apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
    tag: sandbox
  name: techtrends
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
      tag: sandbox
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: techtrends
        tag: sandbox
    spec:
      containers:
      - image: praneethkattaren/techtrends:latest
        imagePullPolicy: IfNotPresent
        name: techtrends
        ports:
        - containerPort: 3111
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
          requests:
            cpu: "250m"
            memory: "64Mi"
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 3111
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 3111
