name: techtrends
tag: sandbox
appName: techtrends-sandbox

namespace:
  name: sandbox

replicaCount: 1

image:
  repository: techtrends
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: techtrends-sandbox-service
  type: ClusterIP
  port: 4111
  targetPort: 3111
  protocol: TCP

resources:
  limits:
    cpu: "500m"
    memory: "128Mi"
  requests:
    cpu: "250m"
    memory: "64Mi"

containerPort: 3111

livenessProbePath: 
  path: /healthz
  port: 3111

readinessProbePath: 
  path: /healthz
  port: 3111